# Generated by Django 5.2.6 on 2025-09-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('jersey', 'Jersey'), ('sepatu', 'Sepatu'), ('bola', 'Bola'), ('aksesoris', 'Aksesoris'), ('merchandise', 'Merchandise')], default='jersey', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
