# Generated by Django 5.2.6 on 2025-10-01 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jersey'), ('sepatu', 'Sepatu'), ('bola', 'Bola'), ('aksesoris', 'Aksesoris'), ('merch', 'Merch')], default='jersey', max_length=20),
        ),
    ]
